### ISSUE TITLE
Error while running npm start on linux

### ISSUE THREAD

**Issue by Advik-B** [Griphcode/Griphitor-IDE#1]
![image](https://user-images.githubusercontent.com/86160411/140058489-c05964f6-8cf4-4e1b-9205-faf3cea47de6.png)

## Here is the log
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v12.22.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle griphitor-desktop@1.2.3~prestart: griphitor-desktop@1.2.3
6 info lifecycle griphitor-desktop@1.2.3~start: griphitor-desktop@1.2.3
7 verbose lifecycle griphitor-desktop@1.2.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle griphitor-desktop@1.2.3~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vscode/Griphitor-IDE/node_modules/.bin:/home/vscode/.vscode-server-insiders/bin/ff1e16eebb93af79fd6d7af1356c4003a120c563-insider/bin:/home/vscode/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/vscode/.local/bin
9 verbose lifecycle griphitor-desktop@1.2.3~start: CWD: /home/vscode/Griphitor-IDE
10 silly lifecycle griphitor-desktop@1.2.3~start: Args: [ '-c', 'electron .' ]
11 info lifecycle griphitor-desktop@1.2.3~start: Failed to exec start script
12 verbose stack Error: griphitor-desktop@1.2.3 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid griphitor-desktop@1.2.3
14 verbose cwd /home/vscode/Griphitor-IDE
15 verbose Linux 5.10.16.3-microsoft-standard-WSL2
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v12.22.7
18 verbose npm  v6.14.15
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error griphitor-desktop@1.2.3 start: `electron .`
23 error spawn ENOENT
24 error Failed at the griphitor-desktop@1.2.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Advik-B** [comment]
If you need more info. just ping me @Advik-B or ```Advik#9471``` on discord

**Comment by Griphcode** [comment]
@Advik-B Hello thanks for your Feedback we are improving our IDE every day. there will be a fix to this problem you will get another ping when done

**Comment by oxmc** [comment]
Thanks for filling an issue @Advik-B!

I changed some code to try and fix it, please re-clone the new code and try running ``npm start`` again.

**Comment by oxmc** [comment]
If that does not fix your issue, try installing ``libnss3-dev``
`sudo apt-get install libnss3-dev`

**Comment by Griphcode** [comment]
@Advik-B  We have fixed your problem. Enjoy and reinstall.

**Comment by Advik-B** [comment]
Thanks @Griphcode
